# Generated by Django 2.2.2 on 2019-07-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=200)),
                ('quantity', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
