# Generated by Django 2.2.2 on 2019-07-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_auto_20190718_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='units',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
